spring.application.name=datanode

# HTTP port - override per instance: --server.port=8082, 8083
server.port=8081

# gRPC server port - override per instance: --spring.grpc.server.port=9092, 9093
spring.grpc.server.port=9091

# Datanode identity - override per instance: --datanode.index=1, 2
datanode.index=0
datanode.peers=http://localhost:8081,http://localhost:8082,http://localhost:8083
