spring.application.name=master

spring.datasource.url=jdbc:postgresql://localhost:5432/spacecloud
spring.datasource.username=lakshyasaharan
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
